{  # pylint: disable=C8101,C8103
    "name": "Gerenciador de Clinica Veterinária",
    "summary": """Adapta o Odoo para ser um sistema que permite
    o gerenciamento de uma clinica veterinária.""",
    "description": """Adapta o Odoo para ser um sistema que permite
    o gerenciamento de uma clinica veterinária.""",
    "version": "13.0.0.0.1",
    "category": "Sales",
    "author": "Felipe Paloschi",
    "contributors": ["Felipe Paloschi <paloschi.eca@gmail.com>"],
    "depends": ["mail", "contacts", "sale_management", "portal"],
    "data": [
        "wizard/appointment_sale.xml",
        "views/animal.xml",
        "views/animal_species.xml",
        "views/animal_breed.xml",
        "views/animal_class.xml",
        "views/animal_appointment.xml",
        "views/sale_order.xml",
        "templates/animals.xml",
        "templates/appointments.xml",
        "reports/appointment_report.xml",
        "data/data.xml",
        "data/animal.class.csv",
        "data/animal.species.csv",
        "data/animal.breed.csv",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "application": True,
}
